spring:
  datasource:
    username: tao
    password: P@ssw0rd
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.98.98:3306/openapi-admin?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: rabbitmq.qfjava.cn
    port: 8800
mybatis:
  type-aliases-package: com.itqf.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
